services:
  fludisplay2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fludisplay2
    ports:
      - "7000:7000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
